apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value
  namespace: v-books
  name: front-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: front
