apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: v-books
spec:
  selector:
    app: api
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
